# Labels based on changed files
# https://github.com/actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'
          - '!CHANGELOG.md'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'
          - 'phpunit.xml'
          - 'phpunit.xml.dist'

src:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'

config:
  - changed-files:
      - any-glob-to-any-file:
          - 'config/**'

database:
  - changed-files:
      - any-glob-to-any-file:
          - 'database/**'

workflows:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'composer.json'
          - 'composer.lock'

middleware:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Middleware/**'

services:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Services/**'

commands:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Console/**'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'SECURITY.md'
          - 'src/Services/HmacVerificationService.php'
          - 'src/Services/SignatureService.php'
          - 'src/Services/SecureKeyGenerator.php'
