name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

        **Before submitting**, please:
        - [Search existing issues](https://github.com/rickeysxhemz/laravel-hmac-auth/issues?q=is%3Aissue) to avoid duplicates
        - [Check discussions](https://github.com/rickeysxhemz/laravel-hmac-auth/discussions) for similar ideas
        - Consider if it fits the project's scope (HMAC authentication)

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific scenario where you need this feature.
      placeholder: "As a [type of user], I want [goal] so that [benefit]..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How would this feature benefit users?
      options:
        - Critical - Blocking adoption/usage
        - High - Significant improvement to workflow
        - Medium - Nice to have enhancement
        - Low - Minor convenience improvement
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or code examples about the feature request here.
